config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	root to: "links#index"
  resources :links do
  	member do
     put "like", to:    "links#upvote"
     put "dislike", to: "links#downvote"
   end	
   resources :comments
  end  
	resources :comments
  resources :users
   get 'users/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
	belongs_to :user
	acts_as_votable
	has_many :comments

	extend FriendlyId
  	friendly_id :title, use: :slugged

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
  has_many :comments

  extend FriendlyId
  friendly_id :username, use: :slugged

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
	

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    #@link = Link.find(params[:link_id])
    #@comment = @link.comments.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment was successfully destroyed."
    redirect_back fallback_location: root_path  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /links
  # GET /links.json
  def index
    @links = Link.all
    #@links = Link.all.order("created_at DESC")
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @links = Link.all
    @link = Link.friendly.find(params[:id])
    @users = User.all
  end

  # GET /links/new
  def new
    #@link = Link.new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    #@link = Link.new(link_params)
    @link = current_user.links.build(link_params)
    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  def upvote
    @link = Link.friendly.find(params[:id])
    @link.upvote_by current_user
    redirect_back(fallback_location: root_path)    #redirect_to :back
  end

  def downvote
    @link = Link.friendly.find(params[:id])
    @link.downvote_from current_user
    redirect_back(fallback_location: root_path) #redirect_to :back
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      #@link = Link.find(params[:id])
      @link = Link.friendly.find(params[:id])
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end

    def current_user?(user)
     user == current_user
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
    @user = User.friendly.find(params[:id])
    @links = Link.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/url_helper.rb
module UrlHelper
  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}" 
  end 

  def root_source_url(url)
    newUrl = URI.parse(url).host
    stringUrl = newUrl.to_s
    stringUrl.sub(/^https?\:\/\//, '').sub(/^www./,'') 
  end 


end 

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_comment.html.erb
			<% if comment.user == current_user -%>
			<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui right floated negative mini button" %>
			<% end %>
			
			<%= content_tag_for(:div, comment) do %>
			<p class="ui floated left content"><%= comment.body %><small><BR/>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.username %></small></p>
<!--
<style type="text/css">
/* unvisited link */
a:link {
    color: green;
}
/* visited link */
a:visited {
    color: blue;
}
/* mouse over link */
a:hover {
    color: red;
    background-color:#ffffcc;
}
/* selected link */
a:active {
    color: black;
}
</style>
-->
	<BR/><p><HR/></p><BR/>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link_id %>
    <%= form.number_field :link_id, id: :comment_link_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :comment_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Radditx2</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.css">


  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script src="jquery.tablesort.js"></script>

  </head>
  <body>

<%#= render 'layouts/partials/topnavbar' %>



<div class="ui inverted <!--pointing--> menu">
  <%= link_to 'Redditx2', root_path, :class=>"active item" %>
  <%= link_to 'Links', links_path, :class=>"item" %>
  <div class="right menu">
    <div class="item">
      <div class="ui icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>
    <% if user_signed_in? %>

        <%= link_to 'Submit link', new_link_path, :class=>'item' %>
        <%= link_to current_user.username, edit_user_registration_path, :class=>'ui inverted olive mini button' %>
        <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, :class=>'item' %>
    <% else %>
        <div class='middle aligned item'><b><i>Guest</i></b></div>
        <%= link_to 'Sign up', new_user_registration_path, :class=>'item' %>
        <%= link_to 'Sign in', new_user_session_path, :class=>'item' %>
    <% end %> 
  </div>
</div><!-- ./pointing menu -->


<div class='ui container'>

		<div class='ui container flash'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div><!-- ./flash -->



    <%= yield %>



	</div><!-- ./container -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.js"></script>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :link_title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :link_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Links</h1>


<script type='text/javascript'>
  $('table').tablesort();
  var tablesort = $('table').data('tablesort');   // Get a reference to it's tablesort instance
  th.sorted.ascending:after {
  content: "  \2191";
  }
  th.sorted.descending:after {
  content: " \2193";
  }
</script>

<table class="ui single line striped sortable celled table">
  <thead>
    <tr>
      <th>Title</th>
      <th class="no-sort">Url</th>
      <th>User</th>
      <th> </th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>


<style type="text/css">
	
/* unvisited link */
a:link {
    color: green;
}

/* visited link */
a:visited {
    color: green;
}

/* mouse over link */
a:hover {
    color: red;
    background-color:#ffffcc;
}

/* selected link */
a:active {
    color: black;
}

</style>


  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><div class='ui medium header'><%= link_to link.title, url_with_protocol(link.url), :class => "" %></div></td>
        <td><%= link_to link.url, url_with_protocol(link.url) %></td>
        <td><%#= link.user_id %><%= link_to link.user.username , user_path(link.user)%></td>
        <td class='center aligned'><%= link_to like_link_path(link), method: :put do %><i class="thumbs up icon"></i><%= link.get_upvotes.size %><% end %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to dislike_link_path(link), method: :put do %><i class="thumbs down icon"></i><%= link.get_downvotes.size %><% end %></td>
        <td><%= link.comments.count %></td>
        <td><%= link_to 'Show', link %></td>
<% if user_signed_in? && current_user.id == link.user.id %>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<style type="text/css">
/* unvisited link */
a:link {
    color: green;
}
/* visited link */
a:visited {
    color: blue;
}
/* mouse over link */
a:hover {
    color: red;
    background-color:#ffffcc;
}
/* selected link */
a:active {
    color: black;
}
</style>

<h2>
  Title:<strong><%#= @link.title %> <a href="<%= url_with_protocol(@link.url) %><%#= @link.url %>"><%= @link.title %></a></strong>
</h2>
<p class="ui mini">Submitted by <%= link_to @link.user.username, user_path(@link.user) %> on <%= @link.created_at.strftime("%m/%d/%Y") %></p>
<p>Url:
  <%#= @link.url %>
  <strong><%= link_to @link.url,@link.url, class: "normallink"  %></strong>
</p>
<p>
<%= link_to like_link_path(@link), method: :put do %><i class="thumbs up icon"></i><%= @link.get_upvotes.size %><% end %>&nbsp;&nbsp;<%= link_to dislike_link_path(@link), method: :put do %><i class="thumbs down icon"></i><%= @link.get_downvotes.size %><% end %>&nbsp;&nbsp;&nbsp;&nbsp;
<% if user_signed_in? && current_user.id == @link.user.id %>
<%= link_to 'Edit', edit_link_path(@link) %> |
<% end %>

<%= link_to 'Back', links_path %>
</p>

<h3 class="">
	<% if @link.comments.count > 0 %>
		<%= @link.comments.count %>
	<%end%>
		<%= 'Comment'.pluralize(@link.comments.count) %> 
</h3>


<div id="ui form">
  <%= render :partial => @link.comments %>
</div>


<%= simple_form_for [@link, Comment.new] do |f| %>
<%#= simple_form_for [@link, @link.comments.new] do |f| %>
  <div class="ui form">
    <%= f.text_area :body, class: "field" %>
  </div>
  <%= f.submit "Add Comment", class: "ui submit button" %>
<% end %>

app/views/users/show.html.erb
<p>User:</p><h2><%= @user.username %></h2> 

<h4> Links added: </h4>

<% @user.links.each do |link| %> 
  

<div class="ui relaxed divided list">
  <div class="item">
    <i class="large github middle aligned icon"></i>
    <div class="content big">
      <%= link_to link.title, link, :class => "header big" %>
      <div class="description mini"><%= link.created_at.strftime("%m / %d / %Y") %></div>
    </div>
  </div>
</div>





<% end %>